version: 0.2

phases:
  install:
    commands:
      - execute as changeset template.yaml {exports }
  pre_build:
    commands:
      - echo "No pre_build needed"
      #- echo "testing the lambda function"

  build:
    commands:
      - aws s3api put-object --bucket $S3_BUCKET --key pipeline-resources/pipeline-roles.yaml --body pipeline-roles.yaml
      - aws s3api put-object --bucket $S3_BUCKET --key pipeline-resources/pipeline-resources.yaml --body pipeline-resources.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

#artifacts:
  #files:
    #- template-output.yaml
